### ISSUE TITLE
website: 64 bit? But what ISA?

### ISSUE THREAD

**Issue by frogtile** [pop-os/website#43]
Download page says, 

> 64-bit processor

In requirements. But what ISA?

**Comment by jacobgkau** [comment]
Just to clarify, are you wanting the website to say something like `x86_64` or `amd64` as opposed to `arm64`/`aarch64`, which are not supported?

**Comment by frogtile** [comment]
Opening this issue was a stupid thing to do in my opinion. How can you guy, engineers, write something like that.


I want it to tell what 64 bit processor. I am not exactly sure how it should be mentioned.


I don't understand your question, the website has no such information currently.

I am running Arch Linux now. Bye.
