### ISSUE TITLE
Readme Docs link broken

### ISSUE THREAD

**Issue by zfreeds** [pop-os/website#69]
Current Text:
Pop!_OS documentation can be viewed at https://pop.system76.com/docs

That link doesn't work.

I'm not sure what the expected URL is so I didn't make a PR yet. Is it supposed to point here? https://support.system76.com/#pop

**Comment by jacobgkau** [comment]
Just https://support.system76.com/ would be the current URL (https://support.system76.com/#pop works, but the #pop anchor doesn't go anywhere right now.)

In the future, this link may be replaced by https://github.com/pop-os/docs, but that new documentation website is still a work in progress.

**Comment by zfreeds** [comment]
Ok, I'll update the link to be that. Still orienting myself in this repo - where would I go if I want to create docs for how to contribute to the OS?

**Comment by jacobgkau** [comment]
> where would I go if I want to create docs for how to contribute to the OS?

The support articles are hosted at https://github.com/system76/docs. As I mentioned, we are in the process of creating separate Pop!_OS-specific documentation at https://github.com/pop-os/docs.

https://github.com/pop-os/pop is the "catch-all" repository for general Pop!_OS issues, although it doesn't contain documentation.

> None of these repo's really describe their scope or purpose.

Most of the repositories (aside from the ones mentioned above) are for a single component. Any repo with a `debian` directory corresponds to one or more apt packages.

**Comment by zfreeds** [comment]
Ah, I understand now. Sorry about that. I hadn't found https://github.com/system76/docs yet and https://github.com/pop-os/docs is somehow broken for me (I can't navigate on the website in its readme).

**Comment by jacobgkau** [comment]
> https://github.com/pop-os/docs is somehow broken for me (I can't navigate on the website in its readme).

Yeah, the URL for the final website hasn't been finalized yet, but it will be moving to an actual domain name instead of the github.io domain.

> It sounds like the concepts I'm considering adding should just go in the readme of the "catch-all" repo.

I think it could work there or in a community support article, depending on the content.

**Comment by zfreeds** [comment]
The content would include (a better version of):
- Where to start
     - Look at cosmic for old DE installation instructions
     - Look at cosmic-epoch for new DE installation instructions
- Developer chat: https://chat.pop-os.org/
- Process for making changes
    - Find the right repo (See repos.md)
    - Make an issue and discuss it until an agreement comes
    - (Not sure who has final say here)
    - Make a PR and get approvals from (?)
    - Your change will be published during the next stable release, which occurs every 6 (?) months.

**Comment by jacobgkau** [comment]
> * (Not sure who has final say here)
> * Make a PR and get approvals from (?)

Every PR to Pop!_OS components requires approval from the engineering team (for code quality and architectural fit) and quality assurance team (for stability and UX sanity.) Anything that significantly impacts the user experience (e.g. new GUI features) may also require approval from the user experience team.

> * Your change will be published during the next stable release, which occurs every 6 (?) months.

This would usually be inaccurate. The six-month release cycle applies to packages inherited from Ubuntu, as well as very large UX changes (such as the introduction of COSMIC with 21.10.) Pop!_OS component updates such as security patches, bug fixes, and even some new features are released regularly (in a rolling-release fashion.)

The Pop!_OS CI server automatically builds the master/main branch of every git repository (every 15 minutes), and all packages from those git branches are published in the [master staging apt repository](http://apt-origin.pop-os.org/staging/master/). Packages are then released from master staging as regular updates via PRs to the repo-release repository, which contains a list of the current version of every package in the release repository: https://github.com/pop-os/repo-release (There is another CI job that checks this list and copies the listed versions of each package from the master staging repo to the release repo.)

Changes can be withheld until the next major release by using a release-specific master branch (e.g. `master_jammy` only builds packages for 22.04, so it would have been the "next release" branch when 21.10 was current), or by building into new packages that are not installed by default (as is the case with the current COSMIC Epoch packages). But this is more of the exception than the norm.

**Comment by zfreeds** [comment]
That is very helpful knowledge! This is exactly why I started trying to document my learnings. Is there a resource you learned from to know all that? I'll add all this to the "[catch-all" repo](https://github.com/pop-os/pop) when I have a chance.

**Comment by zfreeds** [comment]
https://github.com/pop-os/pop/pull/2659

Pr is up for new documentation.

**Comment by jacobgkau** [comment]
Fixed by https://github.com/pop-os/website/pull/70.
