### ISSUE TITLE
https://support.system76.com/articles/install-in-vm/ instructions are wrong (later stuck due to disk size)

### ISSUE THREAD

**Issue by matkoniecz** [pop-os/website#73]
https://support.system76.com/articles/install-in-vm/ claims

> Feel free to just pick the defaults here and click on the "Create" button.

This results in mysterious 

![screen03](https://user-images.githubusercontent.com/899988/199935203-93e19d29-a951-4309-997d-ef193ef22a9f.png)

(hovering over it results in displaying "Disk does not meet the minimum requirement")

**Comment by leviport** [comment]
10gb is not large enough for a Pop install, and that document instructs users to allocate at least 15gb to the VM. Also, the correct place to report issues with those docs is at https://github.com/system76/docs/issues
